name: Tests

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Setup ESLint
        run: |
          npm install
          [ -f .eslintrc.json ]
      - name: ESLint Report
        run: npm run test
